#!/usr/bin/env python3
"""Generate an 8x16 bitmap font as a Rust source array for SAIOS.

Rasterises a monospace TrueType font (DejaVu Sans Mono) into 8x16-pixel
cells for ASCII 0x20-0x7E.  Each glyph is 16 bytes (one byte per row,
MSB = leftmost pixel).  Output: src/graphics/font_data.rs
"""
import sys

OUT = "/mnt/c/Users/Sanjar.Verma/Downloads/Personal/saios/src/graphics/font_data.rs"
FIRST = 0x20
LAST  = 0x7E

def with_pil():
    from PIL import Image, ImageFont, ImageDraw
    # Find a monospace font
    candidates = [
        "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf",
    ]
    font = None
    for c in candidates:
        try:
            font = ImageFont.truetype(c, 14)
            break
        except Exception:
            pass
    if font is None:
        return None
    glyphs = []
    for code in range(FIRST, LAST + 1):
        img = Image.new("L", (8, 16), 0)
        d = ImageDraw.Draw(img)
        d.text((0, 0), chr(code), fill=255, font=font)
        rows = []
        for y in range(16):
            byte = 0
            for x in range(8):
                if img.getpixel((x, y)) > 96:
                    byte |= (1 << (7 - x))
            rows.append(byte)
        glyphs.append(rows)
    return glyphs

def fallback():
    # Minimal procedural fallback: a filled box for every glyph so text is at
    # least visible.  Only used if PIL/fonts unavailable.
    return [[0x00,0x00,0x7E,0x42,0x42,0x42,0x42,0x42,
             0x42,0x42,0x42,0x7E,0x00,0x00,0x00,0x00]
            for _ in range(FIRST, LAST + 1)]

glyphs = None
try:
    glyphs = with_pil()
except Exception as e:
    sys.stderr.write("PIL failed: %s\n" % e)

if glyphs is None:
    sys.stderr.write("Using fallback box font\n")
    glyphs = fallback()

with open(OUT, "w") as f:
    f.write("//! AUTO-GENERATED 8x16 bitmap font (ASCII 0x20-0x7E).\n")
    f.write("//! One glyph = 16 bytes, one byte per row, MSB = leftmost pixel.\n")
    f.write("//! Generated by tools_gen/genfont.py.\n\n")
    f.write("/// First ASCII code point present in the font.\n")
    f.write("pub const FONT_FIRST: u8 = 0x%02X;\n" % FIRST)
    f.write("/// Glyph cell width in pixels.\n")
    f.write("pub const GLYPH_W: usize = 8;\n")
    f.write("/// Glyph cell height in pixels.\n")
    f.write("pub const GLYPH_H: usize = 16;\n\n")
    f.write("/// Glyph bitmaps, indexed by (code - FONT_FIRST).\n")
    f.write("pub static FONT: &[[u8; 16]] = &[\n")
    for code, rows in enumerate(glyphs, start=FIRST):
        byts = ",".join("0x%02X" % b for b in rows)
        f.write("    [%s], // 0x%02X %r\n" % (byts, code, chr(code)))
    f.write("];\n")

print("Wrote %d glyphs to font_data.rs" % len(glyphs))
