[workspace]
members = ["uefi_stub"]
default-members = ["."]

[workspace.package]
version = "0.9.9"
edition = "2024"

[package]
name = "saios"
version.workspace = true
edition.workspace = true
autotests = false

[[bin]]
name = "saios"
path = "src/main.rs"
test = false

[dependencies]
volatile = "0.2"
spin = "0.5"
x86_64 = "0.14"
lazy_static = { version = "1.4", features = ["spin_no_std"] }
linked_list_allocator = "0.10"

[profile.dev]
panic = "abort"
opt-level = 1

[profile.release]
panic = "abort"
opt-level = 2
lto = false
codegen-units = 16
