#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum MemoryError {
    AlreadyInitialized,
    NotInitialized,
    InvalidMemoryMap,
    TooManyFrames,
    FrameOutOfRange,
    DoubleFree,
    InvalidFree,
    OutOfFrames,
    AddressMisaligned,
    MappingExists,
    MappingNotFound,
    NoAddressSpaceSlots,
    HeapOutOfMemory,
    InvalidAllocation,
    OwnershipConflict,
    OwnershipMissing,
    Unsupported,
    PageNotPresent,
    PageNotWritable,
    PageNotExecutable,
    PageNotUserAccessible,
    PageNotAligned,
    PageAlreadyMapped,
    PageTableCorrupted,
    PageTableEntryNotPresent,
    PageTableEntryNotWritable,
    PageTableEntryNotExecutable,
    PageTableEntryNotUserAccessible,
    PageTableEntryAlreadyMapped,
    PageTableEntryCorrupted,
    PageTableEntryNotAligned,
    PageTableEntryInvalid,
    PageTableEntryOutOfRange,
    PageTableEntryNotFound,
    PageTableEntryAlreadyExists,
    PageTableEntryNotAllocated,
    PageTableEntryAllocationFailed,
    PageTableEntryDeallocationFailed,
    PageTableEntryInvalidFlags,
    PageTableEntryInvalidAddress,
    PageTableEntryInvalidLevel,
    PageTableEntryInvalidType,
}

pub type MemoryResult<T> = Result<T, MemoryError>;
