[package]
name = "efi_main"
version = "0.1.0"
edition = "2024"

[features]
default = ["uefi-boot", "uefi-global-allocator"]
uefi-boot = ["uefi/alloc"]
uefi-global-allocator = ["uefi/global_allocator"]

[dependencies]
uefi = { version = "0.38", default-features = false }


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
